# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the 'recommended' set of lints from `package:lints`.
# This set helps identify many issues that may lead to problems when running
# or consuming Dart code, and enforces writing Dart using a single, idiomatic
# style and format.
#
# If you want a smaller set of lints you can change this to specify
# 'package:lints/core.yaml'. These are just the most critical lints
# (the recommended set includes the core lints).
# The core lints are also what is used by pub.dev for scoring packages.

include: package:lints/recommended.yaml
# Uncomment the following section to specify additional rules.

linter:
  rules:
    always_put_control_body_on_new_line: true
    always_specify_types: true
    avoid_catching_erros: true
    avoid_types_on_closure_parameters: false
    avoid_unnecessary_containers: true

    only_throw_errors: true
    empty_catches: true
    join_return_with_assignment: true
    unnecessary_this: false
    avoid_print: false # rever para publicar
    constant_identifier_names: false
    use_key_in_widget_constructors: false
    require_trailing_commas: true
    avoid_unused_constructor_parameters: true
    sort_child_properties_last: true
    always_declare_return_types: true
    directives_ordering: true
    unnecessary_getters_setters: false
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false

analyzer:
  exclude:
    - /dart_test.yaml
# For more information about the core and recommended set of lints, see
# https://dart.dev/go/core-lints

# For additional information about configuring this file, see
# https://dart.dev/guides/language/analysis-options
